String base = 'https://salish.pythonanywhere.com/tiffinwala_app/';
String signup = 'customer/';
String forget = 'resetpassword/';
String doc ='https://docs.google.com/document/d/1Jhv09WCeIMZjMzsAizDEUrA51Sbheg3h8IFbPg6vRVc/edit?usp=drivesdk';
String admin = 'https://salish.pythonanywhere.com/admin';
String verify = 'verify/num_email';
String address = 'address';
String vendor = 'vendor';
String voucher = 'coupon';
String validate = "/validate";
String order = "order";
String review = "/review";
String complain = "/complain";
String picBase = 'https://salish.pythonanywhere.com';