// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81nf2KbyjqL1TCoIbvPI6GgtHsO2TMe8',
    appId: '1:478700872426:android:8b2dd37581686a36fc2d93',
    messagingSenderId: '478700872426',
    projectId: 'tiffin-wala-1d45a',
    storageBucket: 'tiffin-wala-1d45a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCezSLFWg-bm9EL_hzhgdSU_rqHBPqjU',
    appId: '1:478700872426:ios:dffb4eea6ffbe65bfc2d93',
    messagingSenderId: '478700872426',
    projectId: 'tiffin-wala-1d45a',
    storageBucket: 'tiffin-wala-1d45a.appspot.com',
    androidClientId: '478700872426-br6rfc87k07eup7hsr3lcpvtv9u1oqt6.apps.googleusercontent.com',
    iosClientId: '478700872426-s5ppm57hkot0agpfbnbavmsci21pmc37.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiffinWalaCustomer',
  );
}
